apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Values.appid }}-http-vs
  namespace: {{ .Values.appid }}
spec:
  port:
    targetPort: http-vs-port
  to:
    kind: Service
    name: {{ .Values.appid }}
  tls:
    termination: {{ .Values.vstermination }}
    insecureEdgeTerminationPolicy: None
