apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Values.appid }}-usage
  namespace: {{ .Values.appid }}
spec:
  port:
    targetPort: usage-port
  to:
    kind: Service
    name: {{ .Values.appid }}
  tls:
    termination: {{ .Values.usagetermination }}
    insecureEdgeTerminationPolicy: None